// Owner-requested client presentation data. Imported by seed tools, never by UI.
export const demoPrefix = "demo-";
const text = (ar, en) => ({ ar, en });
const empty = () => text("", "");
export function createDemoCatalog() {
  const store = {
    name: text("ماركت البستان · عرض تجريبي", "Al Bustan Market · Demo"),
    description: text(
      "نسخة تجريبية لعرض الكتالوج. المنتجات والأسعار للتوضيح، ويمكن تعديلها بالكامل من لوحة الإدارة.",
      "A demonstration catalog. All products and prices are examples, editable from the admin dashboard.",
    ),
    logoMediaId: null,
    whatsappNumber: "",
    facebookUrl: "",
    currency: "EGP",
    defaultLanguage: "ar",
    branding: { primary: "#15803d", accent: "#ea580c" },
  };
  const categories = [
    ["pantry", "البقالة والحبوب", "Pantry & grains"],
    ["drinks", "المشروبات والعصائر", "Drinks & juices"],
    ["dairy", "الألبان والأجبان", "Dairy & cheese"],
    ["snacks", "السناكس والحلويات", "Snacks & treats"],
    ["coffee", "الشاي والقهوة", "Tea & coffee"],
    ["care", "المنزل والعناية", "Home & care"],
  ].map(([key, ar, en], order) => ({
    id: demoPrefix + key,
    data: {
      name: text(ar, en),
      description: text("قسم تجريبي قابل للتعديل", "Editable demo category"),
      order,
      coverMediaId: null,
      status: "published",
    },
  }));
  // Prices below are whole EGP and converted once to integer minor units.
  const rows = [
    [
      "rice",
      "أرز مصري ١ كجم",
      "Egyptian rice 1 kg",
      "pantry",
      45,
      250,
      970,
      6,
      4,
    ],
    ["pasta", "مكرونة ٤٠٠ جم", "Pasta 400 g", "pantry", 22, 120, 465, 6, 4],
    [
      "sugar",
      "سكر أبيض ١ كجم",
      "White sugar 1 kg",
      "pantry",
      38,
      215,
      840,
      6,
      4,
    ],
    [
      "lentils",
      "عدس أصفر ٥٠٠ جم",
      "Yellow lentils 500 g",
      "pantry",
      48,
      270,
      1050,
      6,
      4,
    ],
    [
      "water",
      "مياه معدنية ١٫٥ لتر",
      "Mineral water 1.5 L",
      "drinks",
      12,
      66,
      250,
      6,
      4,
    ],
    [
      "juice",
      "عصير مانجو ١ لتر",
      "Mango juice 1 L",
      "drinks",
      35,
      195,
      750,
      6,
      4,
    ],
    ["cola", "مشروب غازي ٣٣٠ مل", "Cola 330 ml", "drinks", 18, 100, 380, 6, 4],
    [
      "iced-tea",
      "شاي مثلج بالخوخ",
      "Peach iced tea",
      "drinks",
      28,
      155,
      590,
      6,
      4,
    ],
    [
      "milk",
      "حليب كامل الدسم ١ لتر",
      "Whole milk 1 L",
      "dairy",
      42,
      235,
      910,
      6,
      4,
    ],
    [
      "yogurt",
      "زبادي طبيعي ١٠٥ جم",
      "Plain yogurt 105 g",
      "dairy",
      10,
      55,
      210,
      6,
      4,
    ],
    [
      "cheese",
      "جبن كريمي ٢٠٠ جم",
      "Cream cheese 200 g",
      "dairy",
      65,
      null,
      null,
      null,
      null,
    ],
    [
      "butter",
      "زبدة طبيعية ٢٠٠ جم",
      "Butter 200 g",
      "dairy",
      85,
      null,
      null,
      null,
      null,
    ],
    [
      "biscuits",
      "بسكويت بالشوكولاتة",
      "Chocolate biscuits",
      "snacks",
      15,
      80,
      300,
      6,
      4,
    ],
    [
      "chocolate",
      "شوكولاتة بالحليب ٨٠ جم",
      "Milk chocolate 80 g",
      "snacks",
      32,
      180,
      690,
      6,
      4,
    ],
    [
      "chips",
      "شيبس بطعم الجبنة",
      "Cheese potato chips",
      "snacks",
      12,
      65,
      245,
      6,
      4,
    ],
    [
      "dates",
      "تمور فاخرة ٥٠٠ جم",
      "Premium dates 500 g",
      "snacks",
      95,
      null,
      null,
      null,
      null,
    ],
    [
      "tea",
      "شاي أسود ١٠٠ فتلة",
      "Black tea 100 bags",
      "coffee",
      75,
      420,
      1620,
      6,
      4,
    ],
    [
      "coffee",
      "بن مطحون ٢٥٠ جم",
      "Ground coffee 250 g",
      "coffee",
      125,
      700,
      2700,
      6,
      4,
    ],
    [
      "capsules",
      "علبة ٢٠ كبسولة إسبريسو",
      "Box of 20 espresso capsules",
      "coffee",
      null,
      140,
      790,
      20,
      6,
    ],
    [
      "cocoa",
      "كاكاو خام ١٠٠ جم",
      "Cocoa powder 100 g",
      "coffee",
      55,
      300,
      1150,
      6,
      4,
    ],
    [
      "dish-soap",
      "سائل تنظيف أطباق ٧٥٠ مل",
      "Dishwashing liquid 750 ml",
      "care",
      48,
      270,
      1040,
      6,
      4,
    ],
    [
      "tissues",
      "مناديل ورقية ٢٠٠ منديل",
      "Facial tissues 200 sheets",
      "care",
      25,
      135,
      510,
      6,
      4,
    ],
    [
      "hand-soap",
      "صابون يدين ٢٥٠ مل",
      "Hand soap 250 ml",
      "care",
      38,
      210,
      810,
      6,
      4,
    ],
    [
      "detergent",
      "مسحوق غسيل ١ كجم",
      "Laundry powder 1 kg",
      "care",
      95,
      540,
      2100,
      6,
      4,
    ],
  ];
  const products = rows.map(
    ([key, ar, en, category, unit, box, carton, pieces, boxes], index) => ({
      id: demoPrefix + key,
      data: {
        name: text(ar, en),
        description: text(
          "منتج ضمن كتالوج العرض التجريبي. الأسعار والمواصفات أمثلة ويمكن تعديلها من الإدارة.",
          "A demo catalog product. Prices and specifications are examples and can be edited in the dashboard.",
        ),
        categoryId: demoPrefix + category,
        slug: demoPrefix + key,
        status: "published",
        availability:
          index === 15
            ? "unavailable"
            : [3, 7, 19].includes(index)
              ? "limited"
              : "available",
        unitPriceMinor: unit === null ? null : unit * 100,
        boxPriceMinor: box === null ? null : box * 100,
        cartonPriceMinor: carton === null ? null : carton * 100,
        boxQuantity: pieces,
        cartonBoxQuantity: boxes,
        cartonQuantity: null,
        imageMediaIds: [],
        variants:
          key === "juice"
            ? [
                {
                  id: "mango",
                  label: text("مانجو", "Mango"),
                  kind: "option",
                  unitPriceMinor: 3500,
                  available: true,
                },
                {
                  id: "orange",
                  label: text("برتقال", "Orange"),
                  kind: "option",
                  unitPriceMinor: 3200,
                  available: true,
                },
              ]
            : [],
        discount: [0, 5, 8, 12, 17].includes(index)
          ? {
              kind: "percent",
              value: 10,
              target: "all",
              startsAt: null,
              endsAt: null,
            }
          : index === 20
            ? {
                kind: "fixed",
                value: 500,
                target: "unit",
                startsAt: null,
                endsAt: null,
              }
            : null,
      },
    }),
  );
  const baseOffer = {
    type: "special",
    status: "published",
    description: empty(),
    conditions: text(
      "عرض تجريبي للتوضيح فقط، بدون شراء أو طلبات من الموقع.",
      "Demonstration only. This catalog does not accept purchases or orders.",
    ),
    imageMediaId: null,
    startsAt: null,
    endsAt: null,
    featured: false,
    placement: "none",
    bundleItems: [],
    bundleFinalPriceMinor: null,
    needsReview: false,
    productIds: [],
    specialDisplayPriceMinor: null,
    callout: empty(),
  };
  const offers = [
    {
      id: "demo-welcome",
      data: {
        ...baseOffer,
        name: text(
          "كل احتياجات يومك، في مكان واحد",
          "Your everyday essentials, in one place",
        ),
        description: text(
          "استعرض ٦ أقسام، وقارن أسعار القطعة والعلبة والكرتونة، واكتشف الخصومات والباقات. بيانات العرض تجريبية.",
          "Explore six categories, compare piece, box and carton prices, and discover discounts and bundles. Demo data.",
        ),
        featured: true,
        placement: "hero",
        displayOrder: 0,
        callout: text(
          "كتالوج للمعاينة · أسعار تجريبية",
          "Preview catalog · Sample prices",
        ),
      },
    },
    {
      id: "demo-breakfast",
      data: {
        ...baseOffer,
        type: "bundle",
        name: text("باقة فطار العيلة", "Family breakfast bundle"),
        description: text(
          "حليب + شاي + بسكويت. سعر واحد مستقل للباقة.",
          "Milk, tea and biscuits at one independent bundle price.",
        ),
        displayOrder: 1,
        featured: true,
        bundleItems: [
          { productId: "demo-milk", quantity: 2, unit: "unit" },
          { productId: "demo-tea", quantity: 1, unit: "unit" },
          { productId: "demo-biscuits", quantity: 2, unit: "unit" },
        ],
        bundleFinalPriceMinor: 16500,
      },
    },
    {
      id: "demo-pantry-bundle",
      data: {
        ...baseOffer,
        type: "bundle",
        name: text("باقة أساسيات البيت", "Pantry essentials bundle"),
        description: text(
          "أرز + مكرونة + سكر، بسعر باقة تجريبي واضح.",
          "Rice, pasta and sugar at a simple demo bundle price.",
        ),
        displayOrder: 2,
        bundleItems: [
          { productId: "demo-rice", quantity: 1, unit: "box" },
          { productId: "demo-pasta", quantity: 2, unit: "unit" },
          { productId: "demo-sugar", quantity: 2, unit: "unit" },
        ],
        bundleFinalPriceMinor: 32000,
      },
    },
    {
      id: "demo-care-special",
      data: {
        ...baseOffer,
        name: text("ركن العناية بالبيت", "Home care spotlight"),
        description: text(
          "تعرّف على منتجات النظافة والعناية وأسعارها. التفاصيل قابلة للتعديل من الإدارة.",
          "Explore home care products and prices. Offer details are editable by the owner.",
        ),
        productIds: ["demo-dish-soap", "demo-tissues", "demo-hand-soap"],
        displayOrder: 3,
        callout: text("عرض خاص تجريبي", "Demo special"),
      },
    },
    {
      id: "demo-price-strip",
      data: {
        ...baseOffer,
        name: text(
          "قطعة، علبة، أو كرتونة؟ شوف السعر المناسب",
          "Piece, box or carton? Compare the prices",
        ),
        description: text(
          "مستويات بيع مستقلة، وتفاصيل العبوات داخل صفحة كل منتج.",
          "Independent price levels, with packaging details on each product page.",
        ),
        displayOrder: 4,
        placement: "strip",
        callout: text("أسعار تجريبية", "Sample prices"),
      },
    },
  ];
  return { store, categories, products, offers };
}
